const titles = [
  { title: "Miso Ramen", cuisine: "Japanese", dietTags: "Umami,Comfort" },
  { title: "Sushi Platter", cuisine: "Japanese", dietTags: "Fresh,Seafood" },
  { title: "Okonomiyaki (Japanese Savory Pancake)", cuisine: "Japanese", dietTags: "Hearty,Traditional" },
  { title: "Chicken Tikka Masala", cuisine: "Indian", dietTags: "Spicy,Comfort" },
  { title: "Palak Paneer", cuisine: "Indian", dietTags: "Vegetarian,Healthy" },
  { title: "Butter Chicken (Murgh Makhani)", cuisine: "Indian", dietTags: "Rich,Classic" },
  { title: "Spaghetti Carbonara", cuisine: "Italian", dietTags: "Simple,Classic" },
  { title: "Beef Lasagna", cuisine: "Italian", dietTags: "Hearty,Family" },
  { title: "Risotto ai Funghi (Mushroom Risotto)", cuisine: "Italian", dietTags: "Vegetarian,Creamy" },
  { title: "Tacos al Pastor", cuisine: "Mexican", dietTags: "Street Food,Zesty" },
  { title: "Enchiladas Verdes", cuisine: "Mexican", dietTags: "Spicy,Traditional" },
  { title: "Chiles Rellenos", cuisine: "Mexican", dietTags: "Vegetarian,Authentic" },
  { title: "Ratatouille", cuisine: "French", dietTags: "Vegan,Healthy" },
  { title: "Coq au Vin", cuisine: "French", dietTags: "Classic,Rich" },
  { title: "Moussaka", cuisine: "Greek", dietTags: "Hearty,Traditional" },
  { title: "Spanakopita (Spinach Pie)", cuisine: "Greek", dietTags: "Vegetarian,Savory" },
  { title: "Kung Pao Chicken", cuisine: "Chinese", dietTags: "Spicy,Stir-fry" },
  { title: "Mapo Tofu", cuisine: "Chinese", dietTags: "Spicy,Vegetarian-option" },
  { title: "Dim Sum Selection (Siu Mai & Har Gow)", cuisine: "Chinese", dietTags: "Bite-size,Seafood" },
  { title: "Falafel & Hummus Platter", cuisine: "Middle Eastern", dietTags: "Vegan,Protein-rich" },
  { title: "Shakshuka", cuisine: "Middle Eastern", dietTags: "Vegetarian,Zesty" },
  { title: "Shawarma Wrap", cuisine: "Middle Eastern", dietTags: "Street Food,Spicy" },
  { title: "Texas Style Beef Brisket", cuisine: "American", dietTags: "Smoky,Hearty" },
  { title: "New England Clam Chowder", cuisine: "American", dietTags: "Creamy,Seafood" },
  { title: "New York Style Pizza", cuisine: "American", dietTags: "Classic,Family" },
  { title: "Paella Valenciana", cuisine: "Spanish", dietTags: "Seafood,Impressive" },
  { title: "Gazpacho", cuisine: "Spanish", dietTags: "Vegan,Refreshing" },
  { title: "Feijoada (Brazilian Black Bean Stew)", cuisine: "Brazilian", dietTags: "Rich,Traditional" },
  { title: "Lamb Tagine with Apricots", cuisine: "Moroccan", dietTags: "Sweet-Savory,Aromatic" },
  { title: "Bibimbap", cuisine: "Korean", dietTags: "Balanced,Healthy" }
];
console.log(JSON.stringify(titles));
